### ISSUE TITLE
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of <redis.connection.Connection object at 0x7fbe9e0a6190>> ignored

### ISSUE THREAD

**Issue by xqliang** [andymccurdy/redis-py#398]
Hi, I am using wsgi + apache2 to deploy my python web application. After i upgrade redis-py to 2.7.3, when i restart apache, apache alwarys show an error in apache_error_log: Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of <redis.connection.Connection object at 0x7fbe9e0a6190>> ignored

My dev environment:
Python: 2.6.6
Redis-py: 2.7.3
Apache: Apache/2.2.16 (Debian)

I tried all redis-py<=2.7.2 are ok, and all redis-py>=2.7.3 could cause this problem.

**Comment by naoko** [comment]
I'm getting the same error. 
```
Mon Apr 13 11:47:19.280639 2015] [:error] [pid 7301:tid 139860595107712] Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of Connection<host=localhost,port=6379,db=1>> ignored
[Mon Apr 13 11:47:19.280797 2015] [:error] [pid 7301:tid 139860595107712] Exception AttributeError: AttributeError("'NoneType' object has no attribute 'error'",) in <bound method Connection.__del__ of Connection<host=localhost,port=6379,db=1>> ignored
[Mon Apr 13 11:47:20.177511 2015] [mpm_event:notice] [pid 9420:tid 140441944024960] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
```

**Comment by cank** [comment]
I am running into this as well. Python's documentation has some interesting stuff regarding the __del__ methods:

https://docs.python.org/3/reference/datamodel.html#object.__del__

I am still investigating, but some of these exceptions might just be being munged.

**Comment by pratikgs** [comment]
Also seeing the same error on Python 2.6, Redis 2.10.3
I suspect, it does slow down the apache response to the client ( even if there's no functional side-effect ) ? Any way we can mute this error ?

**Comment by dwoz** [comment]
Why call the disconnect method __del__ anyway? I think users of your library should be encouraged to call disconnect on their own. You could simply provide documentation explaining how to register an atexit method or some other standard cleanup method.

For others who just want to quiet this, in your codebase you can do this:
```python
import redis.connection
def _redis_Connection_del(*args, **kwargs):
    return
redis.connection.Connection.__del__ = _redis_Connection_del

**Comment by erwinyusrizal** [comment]
Any update on this issue? I'm facing the same error using redis 2.10.6 and python 2.7

**Comment by grjones** [comment]
Wouldn't this be terminating wsgi processes on say a graceful restart?

**Comment by eimsbush** [comment]
Same here using python3.8 and
django-redis==4.11.0
hiredis==1.0.1
redis==3.5.0


```python
Exception ignored in: <function Connection.__del__ at 0x7fa5e8552040>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 537, in __del__
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 667, in disconnect
AttributeError: 'NoneType' object has no attribute 'error'
```

**Comment by andymccurdy** [comment]
This is a dupe of #1339. Closing this and continuing the discussion over there.
