### ISSUE TITLE
Cannot import 'BasePipeline'

### ISSUE THREAD

**Issue by saps13** [andymccurdy/redis-py#1078]
I am running into 
`ImportError: cannot import name 'BasePipeline' from 'redis.client' (/usr/local/lib/python3.7/site-packages/redis/client.py)`
at this line
`from rejson import Client, Path`

It is working on redis-py version 2.10.6

**Comment by itamarhaber** [comment]
Hello @saps13 

I believe this issue belongs at https://github.com/RedisLabs/rejson-py :)

**Comment by saps13** [comment]
Yeah you are right. Realized it later. Thanks anyways
