### ISSUE TITLE
Invalid responses responses since 2.7.3

### ISSUE THREAD

**Issue by denik** [andymccurdy/redis-py#376]
After upgrading from 2.7.2 to 2.7.3 (2.7.4, 2.7.5 and 2.7.6 are also affected), my application started crashing with responses from unrelated commands, for example:

```
    redis.zadd(RECONNECT, int(time.time() + RECONNECT_TIME), session_id)
  File "/tmp/cobro-services/websockethub/packages/redis/client.py", line 1093, in zadd
    return self.execute_command('ZADD', name, *pieces)
  File "/tmp/cobro-services/websockethub/packages/redis/client.py", line 376, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/tmp/cobro-services/websockethub/packages/redis/client.py", line 388, in parse_response
    return self.response_callbacks[command_name](response, **options)
TypeError: int() argument must be a string or a number, not 'list'
```

another example:

```
    for message in pubsub.listen():
  File "/tmp/cobro-services/websockethub/packages/redis/client.py", line 1615, in listen
    r = self.parse_response()
  File "/tmp/cobro-services/websockethub/packages/redis/client.py", line 1560, in parse_response
    if nativestr(response[0]) in self.subscribe_commands:
TypeError: 'long' object has no attribute '__getitem__'
```

If I look at the failed responses, I see that they belong to another part of my application, so it seems that connection was not read out properly before it was reused.

I use redis-py with gevent monkey patching. Not sure if matters, but I use pubsub and pipeline. I've tried avoiding pipeline, it did not help. I create a new pubsub instance for each connection and don't share it between [green] threads. I've tried new BlockingConnectionPool class, it did not change anything.
