### PR TITLE
Fix async ping return type hint regression

### LINKED ISSUE #3920: `redis.asyncio.client.Redis.ping` type error introduced in 7.0
To reproduce, install redis-py and run a type-checker on the following snippet:

```python
from redis.asyncio import Redis

async def main() -> None:
    r = Redis()
    await r.ping()
```

Both the latest versions of mypy and ty report a type error due to the return value of the ping method being `Awaitable[bool] | bool`. The expected behaviour is that the above snippet passes type checks.

This is a type regression introduced in https://github.com/redis/redis-py/pull/3789.

### PR DESCRIPTION
**Pull request by veeceey**
## Description

This PR fixes a type checking regression introduced in #3789 where `mypy` and other type checkers incorrectly flag `await r.ping()` as a type error for async Redis clients.

## Problem

The base `ManagementCommands.ping()` method has a return type of `Union[Awaitable[bool], bool]` to support both sync and async clients. However, when async clients inherit this method, type checkers see the union and cannot determine which type will be returned, causing false positive errors like:

```
Incompatible types in "await"
(actual type "str | list[Any] | None", 
 expected type "Awaitable[Any]")
```

## Solution

Added an explicit async override for the `ping()` method in `AsyncManagementCommands` class that:
- Returns `bool` as the type hint (which becomes `Awaitable[bool]` due to `async def`)
- Ensures type checkers understand the async client always returns an awaitable
- Follows the existing pattern used for other async command overrides in the same class

## Testing

- Existing test `tests/test_asyncio/test_commands.py::TestRedisCommands::test_ping` validates the functionality
- The fix resolves the type checking error reported in the issue
- No behavioral changes, only type hint improvements

Fixes #3920

### CODE REVIEW

**Comment by petyaslavova** [comment]
Hi @veeceey! Thanks for working on this and for clearly documenting the underlying typing issue.

That said, we can’t merge this approach as-is. The root problem here isn’t specific to ping()—it’s a broader design issue with how we expose commands across both sync and async clients. If we “fix” this by adding explicit async overrides per command (or duplicating signatures/return types), we’ll end up needing to replicate the entire command surface area twice, and every command with the same union-pattern will have the same typing ambiguity.

In other words: this PR addresses the symptom for one command, but it doesn’t scale, and it would set a precedent that we can’t reasonably maintain.

What we need instead is a consistent strategy that resolves typing for all exposed commands (sync + async) without per-command duplication—then we can apply it across the board in a maintainable way. We don’t have that strategy finalized yet, but it’s the direction we need to take.

So for now we’ll have to decline merging this change, and revisit once we’ve agreed on the broader approach. 
Hopefully, we’ll have time soon to work through a systematic solution.

**Comment by veeceey** [comment]
Thanks @petyaslavova, that makes a lot of sense. You're absolutely right that patching individual commands one at a time isn't sustainable — better to solve it once at the architecture level. If it'd be useful, one direction worth exploring might be auto-generated `.pyi` stubs for the async surface (similar to what httpx and some other libraries do to keep sync/async types in lockstep without duplication). Happy to pitch in whenever you all are ready to tackle the broader approach!
