### PR TITLE
Fix AttributeError on concurrent disconnect in hiredis parser (#2967)

### LINKED ISSUE #2967: Regression in 5.0.1: AttributeError: 'NoneType' object has no attribute 'feed'
### Version
- redis-py: 5.0.1
- redis: 7.0.12

### Platform
- Python 3.10.11 on Windows 11

### Description
This is probably a duplicate of #2349, in which case I'd like to re-open that issue, but I got the same error today with redis-py 5.0.1 (worked fine in 5.0.0):

```
Traceback (most recent call last):
  File "C:\Users\PoByBolek\redis-bug\cache.py", line 137, in _get_raw_data
    return redis.hget(self._name, b'data'), None, None,
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\commands\core.py", line 4946, in hget
    return self.execute_command("HGET", name, key)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 536, in execute_command
    return conn.retry.call_with_retry(
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 537, in <lambda>
    lambda: self._send_command_parse_response(
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 513, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\client.py", line 553, in parse_response
    response = connection.read_response()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\connection.py", line 500, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\_parsers\hiredis.py", line 124, in read_response
    self.read_from_socket()
  File "C:\Users\PoByBolek\redis-bug\venv\lib\site-packages\redis\_parsers\hiredis.py", line 87, in read_from_socket
    self._reader.feed(self._buffer, 0, bufflen)
AttributeError: 'NoneType' object has no attribute 'feed'
```

### PR DESCRIPTION
**Pull request by C1-BA-B1-F3**
## Problem

When multiple threads share a `Redis` client and one thread calls `close()` (e.g. via `with redis:` context manager), `connection_pool.disconnect()` sets `_reader` and `_sock` to `None` on all connections — including those actively in use by other threads. Those threads then crash with:

```
AttributeError: 'NoneType' object has no attribute 'feed'
```

This is a regression introduced in 5.0.1 with the addition of `auto_close_connection_pool` in `Redis.close()`, and is still reproducible on latest code (confirmed by maintainers).

## Root Cause

In `_HiredisParser.read_from_socket()`, `self._reader` and `self._sock` are accessed directly without null checks. When another thread calls `disconnect()` concurrently, these become `None` mid-operation.

Additionally, `read_from_socket()` captured `sock = self._sock` but then used `self._sock.recv_into()` instead of the local `sock` variable, widening the race window.

## Fix

Capture local references to `self._reader` and `self._sock` at the start of each method and check for `None` before use. This converts the unhelpful `AttributeError` into a proper `ConnectionError` with the standard `SERVER_CLOSED_CONNECTION_ERROR` message.

Applied to:
- `_HiredisParser.can_read()`
- `_HiredisParser.read_from_socket()`
- `_HiredisParser.read_response()` (re-checks after `read_from_socket()` in the loop)
- `_AsyncHiredisParser.read_from_socket()`
- `_AsyncHiredisParser.read_response()`

## Tests

5 new regression tests verify that `ConnectionError` (not `AttributeError`) is raised when `_reader` or `_sock` is `None`.

Fixes #2967

---

> [!NOTE]
> **Low Risk**
> Targeted defensive checks on the hiredis read path; behavior unchanged when connections stay connected, with clearer errors on races.
> 
> **Overview**
> Fixes a **thread-safety race** when one thread closes a shared `Redis` client while another is reading: `disconnect()` clears `_reader` and `_sock`, which previously caused **`AttributeError`** (e.g. on `feed`) instead of a proper closed-connection error.
> 
> The **hiredis** sync and async parsers now **snapshot** `_reader` / `_sock` (and use the local socket for `recv_into`), **guard** against `None` at entry and **after** socket reads in `read_response` loops, and raise **`ConnectionError`** with `SERVER_CLOSED_CONNECTION_ERROR` when the connection was torn down mid-operation. Coverage spans `can_read`, `read_from_socket`, and `read_response`.
> 
> **Five regression tests** assert `ConnectionError` when `_reader` or `_sock` is `None`, simulating concurrent disconnect.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 8a6dfed6fcb0ddfccf0cdeb5f3c942c4d865cc1e. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by petyaslavova** [comment]
Hey @C1-BA-B1-F3, I think this behaviour should not be changed, `close()` should close all the connections and we should expect something different. Currently we even have an opened bug that async doesn't follow the same behaviour that will be fixed.
With the reasons mentioned above, I'm closing this PR.
