### ISSUE TITLE
Race condition in connection disconnect 

### ISSUE THREAD

**Issue by victorvorobev** [andymccurdy/redis-py#1148]
Excuse me, but it looks like this issue: https://github.com/andymccurdy/redis-py/issues/732 still occurs in some situations, and unfortunately, I can not actually tell why.
I'm facing this when I'm trying to test out my code using pytest and Travis, current versions of everything are:
**redis-py**: 3.2.0, **redis**: 4.0.9
**Platform**: python: 2.7.14, Ubuntu 14.04
**Stack trace**:
```python
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/redis/client.py:2968: in close
    self.reset()
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/redis/client.py:2958: in reset
    self.connection.disconnect()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Connection<host=localhost,port=6379,db=0>
    def disconnect(self):
        "Disconnects from the Redis server"
        self._parser.on_disconnect()
        if self._sock is None:
            return
        try:
            if os.getpid() == self.pid:
                self._sock.shutdown(socket.SHUT_RDWR)
>           self._sock.close()
E           AttributeError: 'NoneType' object has no attribute 'close'

../../../virtualenv/python2.7.14/lib/python2.7/site-packages/redis/connection.py:587: AttributeError
------------------------------ Captured log call -------------------------------
server.py                  106 WARNING  'NoneType' object has no attribute 'readline'
```

P.S.: If this will help, it looks like with version 2.10.6 everything works smoothly.

**Comment by andymccurdy** [comment]
@victorvorobev Did you ever figure out what was going on here? Are you trying to share a Connection across multiple threads? Connections are not meant to be thread safe.

**Comment by victorvorobev** [comment]
@andymccurdy 
Unfortunately, I'm still not quite sure, but it looks like that `pytest` is the one that should be blamed. My tests were written a bit incorrect and those `connect` and `disconnect` methods were called as setup and teardown methods for every test. After I changed that fact everything became more stable.

I don't know though why everything worked fine with version `2.10.6`.

**Comment by andymccurdy** [comment]
This should have been resolved in redis-py 3.4.0. If you're still having issues, feel free to re-open this.
